import { memberModel } from "../Models/memberModel";

export const PlayerList: memberModel[] = [
    new memberModel("Kevin Hinton", ""),
    new memberModel("Roger Beasley", ""),
    new memberModel("Nathaniel Berry", ""),
    new memberModel("Blake Heuring", ""),
    new memberModel("Kyle Shaffar", ""),
    new memberModel("Mark Burks", ""),
    new memberModel("Cameron Hutchison", ""),
    new memberModel("Alexander Dunn", ""),
    new memberModel("Chris Dunning", ""),
    // new memberModel("Ben Martin", ""),
    // new memberModel("Ben Froemling", ""),
    // new memberModel("Joey Froemling", ""),
    // new memberModel("Blake Rhodes", ""),
    // new memberModel("Brandon Rachelski", ""),
    // new memberModel("Bryce Bigham", ""),
    // new memberModel("Joseph Bartly", ""),
    // new memberModel("Kyle Maloney", ""),
    // new memberModel("Matt Cook", ""),
    // new memberModel("Ryan Everett", ""),
    // new memberModel("Dylan Geile", ""),
    // new memberModel("Kirk Tolleshaug", ""),
    // new memberModel("Nathan Waller", ""),
]